name: Test windows

on:
  pull_request:
    paths:
      - '.github/workflows/test-windows.yml'
      - '.github/workflows/build-any-cuda.yml'
      - '.github/workflows/build-cuda-deps.yml'
      - 'scripts/install-cuda.py'
      - 'cuda/**'
      - 'toolchains/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.filter }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - filter: x86_64-windows-cuda-86
            cuda_code: '128'
          - filter: x86_64-windows-cuda-probe
            cuda_code: '129'
    uses: ./.github/workflows/build-any-cuda.yml
    with:
      filter: ${{ matrix.filter }}
      cuda_code: ${{ matrix.cuda_code }}
    secrets: inherit
  deps:
    name: ${{ matrix.cuda_code }}-deps
    strategy:
      fail-fast: false
      matrix:
        include:
          - cuda_code: '128'
          - cuda_code: '129'
    uses: ./.github/workflows/build-cuda-deps.yml
    with:
      cuda_code: ${{ matrix.cuda_code }}
    secrets: inherit