name: Test release

on:
  pull_request:
  workflow_dispatch:
    inputs:
      llamacpp_version:
        required: false
        default: ''
        type: string
  workflow_call:
    inputs:
      llamacpp_version:
        required: false
        default: ''
        type: string

jobs:
  test:
    name: Test (${{ matrix.platform }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux
            runner: ubuntu-latest
            install: sh install.sh
            llama: ~/.llama-app/llama

          - platform: windows
            runner: windows-latest
            install: pwsh install.ps1
            llama: llama.exe

          - platform: macos
            runner: macos-latest
            install: sh install.sh
            llama: ~/.llama-app/llama
    steps:
      - uses: actions/checkout@v5

      - name: Install
        env:
          LLAMA_BUCKET: ${{ vars.HF_REPO }}
          LLAMA_VERSION: ${{ inputs.llamacpp_version }}
        run: ${{ matrix.install }}

      - name: Test
        run: ${{ matrix.llama }} bench -hf ggml-org/test-model-stories260K
